### ISSUE TITLE
Make overriding easier

### ISSUE THREAD

**Issue by stephendolan** [luckyframework/wordsmith#17]
Our default `inflections.cr` file contains this:
`Wordsmith::Inflector.inflections.irregular("person", "people")`

One would think that adding this afterward would change the behavior:
`Wordsmith::Inflector.inflections.irregular("person", "persons")`

Instead, Wordsmith retains the previous irregular translation. I **kind** of got it to work with:
```crystal
  Inflector.inflections.irregular("person", "people")
  Inflector.inflections.plurals.delete(/(p)erson$/i)
  Inflector.inflections.irregular("person", "persons")
```

But I'm not sure if it really caught every case.

**Comment by stephendolan** [comment]
I've dug into this for a bit to see if there's an "Easy" fix, and I have yet to find something. Here's a code spike for a `remove_irregular` method that removed the original mapping, but seems to ignore the new `person => persons` mapping.

```crystal
  describe "remove irregularities" do
    it "should allow an irregularity to be removed and overwritten" do
      Wordsmith::Inflector.inflections.remove_irregular("person", "people")
      Wordsmith::Inflector.inflections.irregular("person", "persons")

      Wordsmith::Inflector.singularize("persons").should eq "person"
      Wordsmith::Inflector.pluralize("person").should eq "persons"
    end
  end
```

```crystal
      def remove_irregular(singular : String, plural : String)
        @uncountables.delete(singular)
        @uncountables.delete(plural)

        s0 = singular[0]
        srest = singular[1..-1]

        p0 = plural[0]
        prest = plural[1..-1]

        if s0.upcase == p0.upcase
          singular_pattern = /(#{s0})#{srest}$/i
          plural_pattern = /(#{p0})#{prest}$/i

          @singulars.delete(singular_pattern)
          @plurals.delete(plural_pattern)
        else
          singular_uppercase_pattern = /#{s0.upcase}(?i)#{srest}$/
          singular_lowercase_pattern = /#{s0.downcase}(?i)#{srest}$/
          plural_uppercase_pattern = /#{p0.upcase}(?i)#{prest}$/
          plural_lowercase_pattern = /#{p0.downcase}(?i)#{prest}$/

          @singulars.delete(singular_uppercase_pattern)
          @singulars.delete(singular_lowercase_pattern)
          @plurals.delete(plural_uppercase_pattern)
          @plurals.delete(plural_lowercase_pattern)
        end
      end
```

**Comment by stephendolan** [comment]
@matthewmcgarvey I'd really value your input on this problem. Is the way that we're handling enqueuing and storing these inflections simply going to make this kind of thing difficult, or is there some easier solution I'm not seeing in the short term?

Working through this in Discord with a Lucky newcomer was pretty painful for something that feels like it should be pretty simple 😢

**Comment by matthewmcgarvey** [comment]
@stephendolan The code is definitely way more complicated than it appears on the outside 😆 

What do you think about calling that `remove_irregular` inside `irregular`? If it was added for the first time it just wouldn't do anything but "overwriting" irregulars would Just Work™️

**Comment by stephendolan** [comment]
@matthewmcgarvey Yeah, I had played with that but we actually set up bi-directional inflections...

So if I do `irregular("person", "people")` then override with `irregular("person", "peoples")`, I still get left with the pluralize rule from `people` -> `person`.

I'm going to keep thinking about this, but my latest idea is to simply break this file up into separate modules so that it's easier to clear and include them for non-English apps.

**Comment by stephendolan** [comment]
Just so it's in public record, my recommendation ended up being to clear _all_ default inflections and just copy/paste the defaults that made sense for the user's app, like this:

```crystal
# config/inflections.cr

module Wordsmith
  Inflector.inflections.clear

  Inflector.inflections.plural(/$/, "s")
  Inflector.inflections.plural(/s$/i, "s")

  # etc, etc, etc
end
```

That's not honestly that bad, but I guess I need to open a Website ticket to document that a bit better outside of just this library.

**Comment by stephendolan** [comment]
I wouldn't call it drastic since it's in the public API for inflections. I'm down for the refactor, but also want to give folks a path forward in the meantime. This user would have probably just used something else if I hadn't been able to provide a path forward to get around some of the built-in translations that would have been confusing for their userbase.
