### ISSUE TITLE
[Feature Request] release a execute binary which can run directly on terminal.

### ISSUE THREAD

**Issue by zw963** [luckyframework/wordsmith#22]
Hello!

If we consider release a execute binary? maybe i can try do it.

because i have many bash scripts, which exists requirement for convert to camelcase, or from singular to plural etc.

Previous i use ruby which need a portable interpreter, so, i consider it not good, but i find this library, if i can compile
it to a static execute binary, that awesome!

Thank you.

**Comment by jwoertink** [comment]
I would be ok with this :+1:  I'm not sure if it should always build, or be opt-in. What are your thoughts?

**Comment by zw963** [comment]
emmm, good question, maybe should opt-in, or a more better solution, just create a new shard which borrow code from wordsmith?

anyway, this tools is useful for me, because i am very lazy, so, i always write bash code to generate scaffold.
when work with ActiveRecord/Sequel/Avaram which need sigular/plural, camelcase etc.  this help a lot.

i consider ruby/crystal people need it too, but, i never found a tools work well on this.

**Comment by jwoertink** [comment]
If you want to create a separate shard and get it working, then we can take a look at a good way to integrate it after it all works.

**Comment by zw963** [comment]
Hi, @jwoertink ,  i create the first version of `ws` tonight, please check #23 

> I would be ok with this +1 I'm not sure if it should always build, or be opt-in. What are your thoughts?

This should not a issue anymore, because when install as a shards, `ws` never be build.
but when our release a new version use github tag, a packaged precompiled static version 
can be download directly https://github.com/zw963/wordsmith/releases/download/v0.3.1/ws-v0.3.1-x86_64-unknown-linux-musl.tar.gz

**Comment by jwoertink** [comment]
Closed by https://github.com/luckyframework/wordsmith/pull/23
