### ISSUE TITLE
Handle acronyms / all caps with underscore

### ISSUE THREAD

**Issue by robacarp** [luckyframework/wordsmith#5]
```crystal
# src/inflector_test.cr
require "avram"

class Test::ACRONYM
end

include Avram::TableFor

p table_for Test::ACRONYM
```

```terminal
> crystal run src/inflector_test.cr
:test_acrony_ms
```

This caught me by surprise.

**Comment by matthewmcgarvey** [comment]
Link to `table_for` macro: https://github.com/luckyframework/avram/blob/e983b9c19a9746610ed7d1ce53ce9311f117c6b2/src/avram/table_for.cr#L5-L7

Ultimately calls `Wordsmith::Inflector.pluralize`

**Comment by matthewmcgarvey** [comment]
My guess for expected behavior would be that `Test::ACRONYM` becomes `test_acronyms` so if its constant case just underscore and add an "s"? I don't know if "es" rules _have_ to be considered iff it's too much difficulty so `Test::FLASH` could just be `test_flashs`.  That's a real word example which could be confusing but `Test::SSH` is more clear why it might not make sense to see an "es" on the end? 🤷

**Comment by matthewmcgarvey** [comment]
@robacarp Surprisingly, this is not an issue with wordsmith but an issue in avram.

Calling `Wordsmith::Inflector.pluralize("Test::ACRONYM")` returns `"Test::ACRONYMs"` which I believe makes sense and actually what I laid out above including handling of "es" cases.

Where avram messes it up is [when it calls .underscore on the result](https://github.com/luckyframework/avram/blob/e983b9c19a9746610ed7d1ce53ce9311f117c6b2/src/run_macros/infer_table_name.cr#L3). Calling `.underscore` on `ACRONYMs` becomes `acrony_ms`

**Comment by robacarp** [comment]
@matthewmcgarvey thanks for digging into this. The workaround was easy enough for me no doubt. 

Here's where rails does what I'd expect:

```ruby
"HTML".tableize                            # => "htmls"
"Test::ACRONYM".tableize           # => "test/acronyms"
```

I think it's an ordering issue, calling pluralize before underscore instead of the other way around.

**Comment by matthewmcgarvey** [comment]
@robacarp good catch! I opened an issue in Avram with the details and will consider this one closed https://github.com/luckyframework/avram/issues/656
